### ISSUE TITLE
chapter 2: install kube-apiserver instructions don't work

### ISSUE THREAD

**Issue by mikeblas** [PacktPublishing/The-Kubernetes-Bible#1]
On page 38, instructions are given for downloading kube-apiserver, shown in this command:

    $ wget -q --show-progres --https-only -timestamping https://storage.googleapis.com/kubernetes-release/release/v1.14.0.bin/linux/amd64/kube-apiserevr

This just returns without any file being downloaded. Removing the `-q` option shows why:

	$ wget  --show-progres --https-only -timestamping https://storage.googleapis.com/kubernetes-release/release/v1.14.0.bin/linux/amd64/kube-apiserevr
	--2023-02-22 22:03:13--  https://storage.googleapis.com/kubernetes-release/release/v1.14.0.bin/linux/amd64/kube-apiserevr
	Resolving storage.googleapis.com (storage.googleapis.com)... 74.125.195.128, 142.250.107.128, 74.125.135.128, ...
	Connecting to storage.googleapis.com (storage.googleapis.com)|74.125.195.128|:443... connected.
	HTTP request sent, awaiting response... 404 Not Found
	2023-02-22 22:03:13 ERROR 404: Not Found.
	
The text doesn't tell me anything about using this version specifically, or finding a new version. How can I proceed?

**Comment by Packt-Kavyashreek** [comment]
Hi Mikeblas,
Check for the Latest Version: Visit the Kubernetes release page on GitHub or the official Kubernetes website to find the latest version of kube-apiserver. Look for the appropriate URL to download the binary for your platform (in this case, Linux amd64).

Update the URL: Once you've found the URL for the latest version, update the wget command with the new URL.

Retry the Download: After updating the URL, retry the wget command to download the kube-apiserver binary.

Here's an example of how the updated wget command might look:
wget --show-progress --https-only --timestamping <new-url>

**Comment by mikeblas** [comment]
Still doesn't work.

**Comment by GeminiAgaloos** [comment]
Hi @mikeblas, looks like there's a couple of typos in the URL:
v1.14.0.bin should be v1.14.0/bin
Also, kube-apiserver is misspelled as kube-apiserevr.

This should be the correct URL (and should open a download dialog if accessed directly via a web-browser):
https://storage.googleapis.com/kubernetes-release/release/v1.14.0/bin/linux/amd64/kube-apiserver

I tried the following command and it worked:
`wget --show-progress --https-only --timestamping https://storage.googleapis.com/kubernetes-release/release/v1.14.0/bin/linux/amd64/kube-apiserver`

**Comment by mikeblas** [comment]
Thank you for the thoughtful response! Unfortunately, I've since returned the book for a refund.
